board: 6x CNC Controller
name: 6x Default

arc_tolerance_mm: 0.002
junction_deviation_mm: 0.020
report_inches: false

stepping:
  engine: I2S_STREAM
  idle_ms: 255
  pulse_us: 10
  dir_delay_us: 1
  disable_delay_us: 1

axes:

  x:
    steps_per_mm: 640
    max_rate_mm_per_min: 4600
    acceleration_mm_per_sec2: 1200
    max_travel_mm: 484.000
    soft_limits: true
    homing:
      cycle: 2
      positive_direction: true
      mpos_mm: 0 
      feed_mm_per_min: 100.000
      seek_mm_per_min: 400.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.33:high
      hard_limits: false
      pulloff_mm: 0.5
      standard_stepper:
        step_pin: I2SO.2
        direction_pin: I2SO.1:high
        disable_pin: I2SO.0
      

  y:
    steps_per_mm: 640
    max_rate_mm_per_min: 4600
    acceleration_mm_per_sec2: 1200
    max_travel_mm: 493.000
    soft_limits: true
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: -493.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 400.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.32:high:pd
      hard_limits: false
      pulloff_mm: 5.000
      standard_stepper:
        step_pin: I2SO.5
        direction_pin: I2SO.4:low
        disable_pin: I2SO.7


  z:
    steps_per_mm: 640
    max_rate_mm_per_min: 4000
    acceleration_mm_per_sec2: 1200

    max_travel_mm: 275.000
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 0
      feed_mm_per_min: 100.000
      seek_mm_per_min: 400.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_pos_pin: gpio.35:high
      hard_limits: false
      pulloff_mm: 2.0
      standard_stepper:
        step_pin: I2SO.13
        direction_pin: I2SO.12:low
        disable_pin: I2SO.15
        
  b:
    steps_per_mm: 55.555
    max_rate_mm_per_min: 2600
    acceleration_mm_per_sec2: 800

    motor0:
      standard_stepper:
        step_pin: I2SO.10
        direction_pin: I2SO.9:low
        disable_pin: I2SO.8


i2so:
  bck_pin: gpio.22
  data_pin: gpio.21
  ws_pin: gpio.17

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  card_detect_pin: NO_PIN
  cs_pin: gpio.5
  
control:
  fault_pin: gpio.26:low:pu
  safety_door_pin: NO_PIN
  estop_pin: gpio.36:high
  feed_hold_pin: gpio.27:low:pu  
  cycle_start_pin: gpio.2:low:pu
  macro0_pin: NO_PIN
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN

macros:
  startup_line0: g21 
  startup_line1: $message/level=error
  macro0: 
  macro1: 
  macro2:
  macro3:
  after_homing: M52P0
  after_reset: M52P0
  after_unlock: M52P0

user_outputs:
  digital0_pin: gpio.12
  digital1_pin: gpio.4


probe:
  pin: gpio.34:low
  check_mode_start: true
  hard_stop: false
  toolsetter_pin: gpio.39:low
  

coolant:
  flood_pin:I2SO.18
  mist_pin: I2SO.16
  delay_ms: 0
start:
  must_home: true

atc_custom:
  ets_mpos_mm: -22.000 -22.000 -293.000
  ets_rapid_z_offset_mm: 10.000
  ets_probe_overtravel_mm: 4.000
  gauge_line_length_mm: 63.666
  manual_gauge_range_mm: 25.000 200.000
  tool_holder_pulloff_mm: 0.0 35.0 15.0 0.0 0.0 0.0
  first_tool_number: 2
  tool_count: 6              
  gauge_filename: "Tool_Gauges_Lengths.txt" 
  slot1_mpos_mm: -1.100 -483.300 -176
  slot2_mpos_mm: 100.200 -483.300 -174.5
  slot3_mpos_mm: -198.100 -484.300 -173.1
  slot4_mpos_mm: -283.800 -484.700 -172.8
  slot5_mpos_mm: -380.000 -484.700 -172.9
  slot6_mpos_mm: -477.200 -484.700 -172.3


  
uart1:
  txd_pin: gpio.15
  rxd_pin: gpio.16
  rts_pin: gpio.14
  baud: 38400
  mode: 8N1

Cumark:
  atc: atc_custom
  poll_ms: 100
  uart_num: 1
  modbus_id: 1
  tool_num: 0
  spinup_ms: 3000
  spindown_ms: 3000
  speed_map: 0=0.000% 0=3.000% 540=3.000% 18000=100.000%
  off_on_alarm: true
  adaptive_feed_floor_percent: 10
  adaptive_feed_min_percent: 25
  adaptive_feed_max_percent: 150
  adaptive_feed_gain_down: 2.0
  adaptive_feed_gain_up: 0.5
  adaptive_feed_deadband_percent: 2
  adaptive_feed_aggressive_step: 150